//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : UserData
	/// Data Source    : localhost
	/// Server Version : 16.00.0950
	/// </summary>
	public partial class UserDataDB : LinqToDB.Data.DataConnection
	{
		public ITable<DailyTx> DailyTxes { get { return this.GetTable<DailyTx>(); } }

		public UserDataDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public UserDataDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public UserDataDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public UserDataDB(LinqToDBConnectionOptions<UserDataDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="DailyTx")]
	public partial class DailyTx
	{
		[Column, Nullable] public string    UserId      { get; set; } // nvarchar(50)
		[Column, Nullable] public DateTime? TxDate      { get; set; } // date
		[Column, Nullable] public decimal?  TotalAmount { get; set; } // decimal(18, 2)
		[Column, Nullable] public int?      TxCount     { get; set; } // int
	}
}
